---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: tkn
  labels:
    app.kubernetes.io/version: {{ .Chart.Version }}
{{- if .Values.annotations }}
  annotations:
  {{- .Values.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  description: >-
    This task performs operations on Tekton resources using tkn.
  
  workspaces:
    - name: kubeconfig_dir
      optional: true
      description: >-
        An optional workspace that allows you to provide a .kube/config
        file for tkn to access the cluster. The file should be placed at
        the root of the Workspace with name kubeconfig.

  params:
    - name: TKN_IMAGE
      description: tkn CLI container image to run this task
      default: registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8@sha256:72394dfaed68c4b6b490c3c971fb1d9f0139f8656f6672b55b8e02ea98d1298d
    - name: SCRIPT
      description: tkn CLI script to execute
      type: string
      default: "tkn $@"
    - name: ARGS
      type: array
      description: tkn CLI arguments to run
      default: ["--help"]
   
  stepTemplate:
    env:
{{- $variables := list
      "params.TKN_IMAGE"
      "params.SCRIPT"
      "workspaces.kubeconfig_dir.bound"
      "workspaces.kubeconfig_dir.path"
}}
{{- include "environment" ( list $variables ) | nindent 6 }}

  steps:
{{- include "load_scripts" ( list . "tkn-" ) | nindent 4 }}

    - name: tkn
      image: "$(params.TKN_IMAGE)"
      env:
        - name: HOME
          value: /tekton/home
      command:
        - /scripts/tkn-client.sh
      args: ["$(params.ARGS)"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      volumeMounts:
        - name: scripts-dir
          mountPath: /scripts

  volumes:
    - name: scripts-dir
      emptyDir: {}